#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: sumanth55/kubes
        ports:
        - containerPort: 80 
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
        port: 80
        targetPort: 8080
        nodePort: 31000
  type: NodePort          